# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models, migrations


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aceptados',
            fields=[
                ('id', models.AutoField(serialize=False, verbose_name='ID', auto_created=True, primary_key=True)),
                ('aceptado', models.SmallIntegerField(blank=True, null=True)),
                ('alta_date_created', models.DateTimeField(auto_now_add=True)),
                ('baja_date_created', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='AlumnoCalificacion',
            fields=[
                ('id', models.AutoField(serialize=False, verbose_name='ID', auto_created=True, primary_key=True)),
                ('calificacion', models.IntegerField(blank=True, null=True)),
                ('calificacion_letra', models.CharField(max_length=100, blank=True)),
                ('revalidacion', models.SmallIntegerField(blank=True, null=True)),
                ('ciclo', models.CharField(max_length=50, blank=True)),
                ('alta_date_created', models.DateTimeField(auto_now_add=True)),
                ('baja_date_created', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['calificacion'],
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='AlumnoPrevio',
            fields=[
                ('id', models.AutoField(serialize=False, verbose_name='ID', auto_created=True, primary_key=True)),
                ('alta_date_created', models.DateTimeField(auto_now_add=True)),
                ('baja_date_created', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='AlumnoProyecto',
            fields=[
                ('id', models.AutoField(serialize=False, verbose_name='ID', auto_created=True, primary_key=True)),
                ('concluyo', models.SmallIntegerField(blank=True, null=True)),
                ('calificado', models.SmallIntegerField(blank=True, null=True)),
                ('alta_date_created', models.DateTimeField(auto_now_add=True)),
                ('baja_date_created', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Alumnos',
            fields=[
                ('id', models.AutoField(serialize=False, verbose_name='ID', auto_created=True, primary_key=True)),
                ('nom_alumno', models.CharField(max_length=200, db_index=True, verbose_name='Nombre')),
                ('apellido_materno', models.CharField(max_length=50)),
                ('apellido_paterno', models.CharField(max_length=50)),
                ('curp', models.CharField(max_length=25, blank=True)),
                ('edad', models.IntegerField(blank=True, null=True)),
                ('sexo', models.CharField(max_length=10, blank=True, verbose_name='genero')),
                ('edo_civil', models.CharField(max_length=50, blank=True, verbose_name='Estado Civil')),
                ('tipo_sangre', models.CharField(max_length=10, blank=True)),
                ('servicio_medico', models.SmallIntegerField(blank=True, null=True)),
                ('instituto', models.CharField(max_length=50, blank=True)),
                ('num_afiliacion', models.CharField(max_length=50, blank=True, verbose_name='No De Afiliación')),
                ('generacion', models.IntegerField(blank=True, null=True)),
                ('tipo', models.CharField(max_length=50, blank=True)),
                ('no_expediente', models.CharField(max_length=50, blank=True)),
                ('matricula', models.CharField(max_length=20, unique=True, blank=True, null=True)),
                ('condicionado', models.SmallIntegerField(verbose_name='Status', blank=True, null=True)),
                ('domicilio', models.CharField(max_length=100, blank=True)),
                ('colonia', models.CharField(max_length=50, blank=True)),
                ('localidad', models.CharField(max_length=50, blank=True)),
                ('municipio', models.CharField(max_length=50, blank=True, null=True)),
                ('cp', models.CharField(max_length=50, blank=True, verbose_name='Codigo Postal')),
                ('telefono', models.CharField(max_length=50, blank=True)),
                ('lugar_nac', models.CharField(max_length=50, verbose_name='Lugar de nacimiento', blank=True, null=True)),
                ('fecha_nacimiento', models.DateTimeField(blank=True, null=True)),
                ('alergias', models.CharField(max_length=50, blank=True)),
                ('enfermedades', models.CharField(max_length=50, blank=True, verbose_name='Padecimientos')),
                ('contacto_emergencia', models.CharField(max_length=50, blank=True)),
                ('contacto_domicilio', models.CharField(max_length=100, blank=True)),
                ('contacto_tel', models.CharField(max_length=50, blank=True)),
                ('nombre_tutor', models.CharField(max_length=50, blank=True)),
                ('nombre_materno', models.CharField(max_length=50, blank=True)),
                ('domicilio_tutor', models.CharField(max_length=100, blank=True)),
                ('localidad_tutor', models.CharField(max_length=50, blank=True)),
                ('telefono_tutor', models.CharField(max_length=50, blank=True)),
                ('ocupacion_tutor', models.CharField(max_length=50, blank=True)),
                ('sueldo_mensual', models.DecimalField(max_digits=19, blank=True, null=True, decimal_places=4)),
                ('domicilio_madre', models.CharField(max_length=100, blank=True)),
                ('localidad_madre', models.CharField(max_length=50, blank=True)),
                ('telefono_madre', models.CharField(max_length=50, blank=True)),
                ('trabaja_actualmente', models.BooleanField(default=False)),
                ('puesto', models.CharField(max_length=50, blank=True)),
                ('sueldo_mensual_alumno', models.DecimalField(max_digits=19, blank=True, null=True, decimal_places=4)),
                ('transporte', models.SmallIntegerField(blank=True, null=True)),
                ('transporte_universidad', models.SmallIntegerField(blank=True, null=True)),
                ('deporte_practica', models.CharField(max_length=50, blank=True)),
                ('musica', models.BooleanField(default=False)),
                ('teatro', models.BooleanField(default=False)),
                ('declamacion', models.BooleanField(default=False)),
                ('oratoria', models.BooleanField(default=False)),
                ('otro_interes', models.BooleanField(default=False, verbose_name='otros')),
                ('credencial', models.SmallIntegerField(blank=True, null=True)),
                ('foto', models.ImageField(upload_to='fotos', blank=True)),
                ('firma', models.ImageField(upload_to='firma', blank=True)),
                ('anio_egreso', models.CharField(max_length=5, verbose_name='Egreso', blank=True, null=True)),
                ('promedio_bachiller', models.DecimalField(max_digits=3, verbose_name='Promedio', blank=True, null=True, decimal_places=3)),
                ('password', models.CharField(max_length=50, blank=True)),
                ('email', models.EmailField(max_length=75)),
                ('is_deuda', models.BooleanField(default=False)),
                ('alta_date_created', models.DateTimeField(auto_now_add=True)),
                ('baja_date_created', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'permissions': (('can_view_servicios_escolares', 'Servicios Escolares'),),
                'ordering': ['nom_alumno'],
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='AlumnosAsesorados',
            fields=[
                ('id', models.AutoField(serialize=False, verbose_name='ID', auto_created=True, primary_key=True)),
                ('nombre', models.CharField(max_length=50, blank=True)),
                ('alta_date_created', models.DateTimeField(auto_now_add=True)),
                ('baja_date_created', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Aulas',
            fields=[
                ('id', models.AutoField(serialize=False, verbose_name='ID', auto_created=True, primary_key=True)),
                ('nom_aula', models.CharField(max_length=50, blank=True)),
                ('edificio', models.CharField(max_length=50, blank=True)),
                ('alta_date_created', models.DateTimeField(auto_now_add=True)),
                ('baja_date_created', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Bajas',
            fields=[
                ('id', models.AutoField(serialize=False, verbose_name='ID', auto_created=True, primary_key=True)),
                ('motivo', models.CharField(max_length=200, blank=True)),
                ('observaciones', models.CharField(max_length=200, blank=True, null=True)),
                ('alta_date_created', models.DateTimeField(auto_now_add=True)),
                ('baja_date_created', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Becas',
            fields=[
                ('id', models.AutoField(serialize=False, verbose_name='ID', auto_created=True, primary_key=True)),
                ('nom_beca', models.CharField(max_length=50, blank=True)),
                ('limite_becas_total', models.IntegerField(verbose_name='Limite de becas al 100%(Total)', blank=True, null=True)),
                ('restriccion_becas', models.BooleanField(default=False, verbose_name='Restringir capturas de becas(Nuevo Ingreso)')),
                ('restriccion_promedios', models.BooleanField(default=False, verbose_name='Estatus de candados por promedio')),
                ('promedio_80_84', models.CharField(max_length=50, blank=True, null=True)),
                ('promedio_85_89', models.CharField(max_length=50, blank=True, null=True)),
                ('promedio_90_94', models.CharField(max_length=50, blank=True, null=True)),
                ('promedio_95_100', models.CharField(max_length=50, blank=True, null=True)),
                ('alta_date_created', models.DateTimeField(auto_now_add=True)),
                ('baja_date_created', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('alumnos', models.ManyToManyField(to='academica.Alumnos', blank=True, null=True)),
            ],
            options={
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Biblioteca',
            fields=[
                ('id', models.AutoField(serialize=False, verbose_name='ID', auto_created=True, primary_key=True)),
                ('observacion', models.CharField(max_length=250, verbose_name='Observaciones', blank=True, null=True)),
                ('alta_date_created', models.DateTimeField(verbose_name='Alta de adeudo', blank=True, null=True)),
                ('baja_date_created', models.DateTimeField(verbose_name='Baja de adeudo', blank=True, null=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Deuda Activa')),
                ('alumno', models.ForeignKey(to='academica.Alumnos', unique=True)),
            ],
            options={
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Calificaciones',
            fields=[
                ('id', models.AutoField(serialize=False, verbose_name='ID', auto_created=True, primary_key=True)),
                ('primera', models.DecimalField(max_digits=3, verbose_name='1ra Calificacion', blank=True, null=True, decimal_places=0)),
                ('status1', models.IntegerField(verbose_name='Status', blank=True, null=True)),
                ('segunda', models.DecimalField(max_digits=3, verbose_name='2da Calificacion', blank=True, null=True, decimal_places=0)),
                ('status2', models.IntegerField(verbose_name='Status', blank=True, null=True)),
                ('tercera', models.DecimalField(max_digits=3, verbose_name='3ra Calificacion', blank=True, null=True, decimal_places=0)),
                ('status3', models.IntegerField(verbose_name='Status', blank=True, null=True)),
                ('cuarta', models.DecimalField(max_digits=3, verbose_name='4ta Calificacion', blank=True, null=True, decimal_places=0)),
                ('status4', models.IntegerField(verbose_name='Status', blank=True, null=True)),
                ('quinta', models.DecimalField(max_digits=3, verbose_name='5ta Calificacion', blank=True, null=True, decimal_places=0)),
                ('status5', models.IntegerField(verbose_name='Status', blank=True, null=True)),
                ('sexta', models.DecimalField(max_digits=3, verbose_name='6ta Calificacion', blank=True, null=True, decimal_places=0)),
                ('status6', models.IntegerField(verbose_name='Status', blank=True, null=True)),
                ('final', models.DecimalField(max_digits=3, verbose_name='Calificacion Final', blank=True, null=True, decimal_places=0)),
                ('status_final', models.IntegerField(verbose_name='Status', blank=True, null=True)),
                ('borrado', models.IntegerField(blank=True, null=True)),
                ('tipoacreditacion', models.IntegerField(blank=True, null=True)),
                ('actualizado', models.DateTimeField(blank=True, null=True)),
                ('fecha_revalidacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_modificacion', models.DateTimeField(null=True, auto_now_add=True)),
                ('modulo', models.IntegerField(blank=True, null=True)),
                ('login', models.CharField(max_length=20, blank=True, null=True)),
                ('claveubicacion', models.CharField(max_length=10, blank=True, null=True)),
                ('id_curso', models.IntegerField(blank=True, null=True)),
                ('fecha_extraordinario', models.DateTimeField(blank=True, null=True)),
                ('alta_date_created', models.DateTimeField(null=True, auto_now_add=True)),
                ('baja_date_created', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Carreras',
            fields=[
                ('id', models.AutoField(serialize=False, verbose_name='ID', auto_created=True, primary_key=True)),
                ('nom_carrera', models.CharField(max_length=50, blank=True)),
                ('clave', models.CharField(max_length=50, unique=True, blank=True)),
                ('abreviatura', models.CharField(max_length=50, blank=True)),
                ('alta_date_created', models.DateTimeField(auto_now_add=True)),
                ('baja_date_created', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['nom_carrera'],
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='CentroComputo',
            fields=[
                ('id', models.AutoField(serialize=False, verbose_name='ID', auto_created=True, primary_key=True)),
                ('observacion', models.CharField(max_length=250, verbose_name='Observaciones', blank=True, null=True)),
                ('alta_date_created', models.DateTimeField(verbose_name='Alta de adeudo', blank=True, null=True)),
                ('baja_date_created', models.DateTimeField(verbose_name='Baja de adeudo', blank=True, null=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Deuda Activa')),
                ('alumno', models.ForeignKey(to='academica.Alumnos', unique=True)),
            ],
            options={
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='CicloSemestral',
            fields=[
                ('id', models.AutoField(serialize=False, verbose_name='ID', auto_created=True, primary_key=True)),
                ('clave', models.CharField(max_length=50, unique=True, blank=True)),
                ('ciclo_sep', models.CharField(max_length=50, blank=True, verbose_name='Ciclo SEP')),
                ('anio', models.IntegerField(verbose_name='Año', blank=True, null=True)),
                ('periodo', models.IntegerField(blank=True, null=True)),
                ('fecha_inicio', models.DateTimeField(blank=True, null=True)),
                ('fecha_termino', models.DateTimeField(blank=True, null=True)),
                ('vigente', models.BooleanField(default=False)),
                ('fecha_inicio_programacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_fin_programacion', models.DateTimeField(blank=True, null=True)),
                ('alta_date_created', models.DateTimeField(auto_now_add=True)),
                ('baja_date_created', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['clave'],
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Contabilidad',
            fields=[
                ('id', models.AutoField(serialize=False, verbose_name='ID', auto_created=True, primary_key=True)),
                ('observacion', models.CharField(max_length=250, verbose_name='Observaciones', blank=True, null=True)),
                ('alta_date_created', models.DateTimeField(verbose_name='Alta de adeudo')),
                ('baja_date_created', models.DateTimeField(verbose_name='Baja de adeudo', blank=True, null=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Deuda Activa')),
                ('alumno', models.ForeignKey(to='academica.Alumnos', unique=True)),
            ],
            options={
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='CreditoEducativo',
            fields=[
                ('id', models.AutoField(serialize=False, verbose_name='ID', auto_created=True, primary_key=True)),
                ('estado', models.SmallIntegerField(blank=True, null=True)),
                ('alta_date_created', models.DateTimeField(auto_now_add=True)),
                ('baja_date_created', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('alumno', models.ForeignKey(to='academica.Alumnos')),
                ('semestre', models.ForeignKey(to='academica.CicloSemestral')),
            ],
            options={
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Cursos',
            fields=[
                ('id', models.AutoField(serialize=False, verbose_name='ID', auto_created=True, primary_key=True)),
                ('nombre', models.CharField(max_length=50, blank=True)),
                ('hora', models.DateTimeField(blank=True, null=True)),
                ('instructor', models.CharField(max_length=50, blank=True, null=True)),
                ('alta_date_created', models.DateTimeField(auto_now_add=True)),
                ('baja_date_created', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Divisiones',
            fields=[
                ('id', models.AutoField(serialize=False, verbose_name='ID', auto_created=True, primary_key=True)),
                ('division', models.CharField(max_length=50, blank=True)),
                ('alta_date_created', models.DateTimeField(auto_now_add=True)),
                ('baja_date_created', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('carreras', models.ManyToManyField(to='academica.Carreras', blank=True, null=True)),
            ],
            options={
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Documentos',
            fields=[
                ('id', models.AutoField(serialize=False, verbose_name='ID', auto_created=True, primary_key=True)),
                ('nombre', models.CharField(max_length=50, blank=True)),
                ('alta_date_created', models.DateTimeField(auto_now_add=True)),
                ('baja_date_created', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('alumnos', models.ManyToManyField(to='academica.Alumnos', blank=True, null=True)),
            ],
            options={
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Empresas',
            fields=[
                ('id', models.AutoField(serialize=False, verbose_name='ID', auto_created=True, primary_key=True)),
                ('nombre', models.CharField(max_length=200, blank=True, null=True)),
                ('tipo', models.CharField(max_length=50, blank=True, null=True)),
                ('tamano', models.CharField(max_length=50, blank=True, null=True)),
                ('municipio', models.CharField(max_length=50, blank=True, null=True)),
                ('clave', models.CharField(max_length=50, unique=True, blank=True, null=True)),
                ('direccion', models.CharField(max_length=200, blank=True, null=True)),
                ('telefono', models.CharField(max_length=250, blank=True, null=True)),
                ('alta_date_created', models.DateTimeField(auto_now_add=True)),
                ('baja_date_created', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='EncuestaEgresados',
            fields=[
                ('id', models.AutoField(serialize=False, verbose_name='ID', auto_created=True, primary_key=True)),
                ('nombre', models.CharField(max_length=50, blank=True)),
                ('sexo', models.CharField(max_length=50, blank=True)),
                ('carrera', models.CharField(max_length=50, blank=True)),
                ('telefono', models.CharField(max_length=50, blank=True)),
                ('edad', models.CharField(max_length=50, blank=True)),
                ('correo_electronico', models.CharField(max_length=50, blank=True)),
                ('estado_civil', models.CharField(max_length=50, blank=True)),
                ('preg_9', models.CharField(max_length=50, blank=True)),
                ('porque_preg_9', models.CharField(max_length=50, blank=True)),
                ('preg_10', models.CharField(max_length=50, blank=True)),
                ('preg_11', models.CharField(max_length=50, blank=True)),
                ('preg_12', models.CharField(max_length=50, blank=True)),
                ('preg_13', models.CharField(max_length=50, blank=True)),
                ('porque_preg_13', models.CharField(max_length=200, blank=True)),
                ('preg_14', models.CharField(max_length=50, blank=True)),
                ('porque_preg_14', models.CharField(max_length=200, blank=True)),
                ('preg_15', models.CharField(max_length=50, blank=True)),
                ('preg_16', models.CharField(max_length=100, blank=True)),
                ('preg_17', models.CharField(max_length=50, blank=True)),
                ('preg_18', models.CharField(max_length=200, blank=True)),
                ('preg_19', models.CharField(max_length=50, blank=True)),
                ('preg_20', models.CharField(max_length=100, blank=True)),
                ('preg_21_1', models.CharField(max_length=50, blank=True)),
                ('preg_21_2', models.CharField(max_length=50, blank=True)),
                ('preg_21_3', models.CharField(max_length=50, blank=True)),
                ('preg_21_4', models.CharField(max_length=50, blank=True)),
                ('preg_21_5', models.CharField(max_length=50, blank=True)),
                ('preg_21_6', models.CharField(max_length=50, blank=True)),
                ('preg_21_7', models.CharField(max_length=50, blank=True)),
                ('preg_21_8', models.CharField(max_length=50, blank=True)),
                ('preg_21_9', models.CharField(max_length=50, blank=True)),
                ('preg_21_10', models.CharField(max_length=50, blank=True)),
                ('preg_22', models.CharField(max_length=50, blank=True)),
                ('preg_23', models.CharField(max_length=50, blank=True)),
                ('preg_24', models.CharField(max_length=50, blank=True)),
                ('preg_25', models.CharField(max_length=50, blank=True)),
                ('preg_26', models.CharField(max_length=50, blank=True)),
                ('preg_27', models.CharField(max_length=50, blank=True)),
                ('preg_28', models.CharField(max_length=50, blank=True)),
                ('porque_preg_28', models.CharField(max_length=200, blank=True)),
                ('preg_29', models.CharField(max_length=50, blank=True)),
                ('preg_30', models.CharField(max_length=50, blank=True)),
                ('porque_preg_30', models.CharField(max_length=200, blank=True)),
                ('preg_31_1', models.CharField(max_length=50, blank=True)),
                ('preg_31_2', models.CharField(max_length=50, blank=True)),
                ('preg_31_3', models.CharField(max_length=50, blank=True)),
                ('preg_31_4', models.CharField(max_length=50, blank=True)),
                ('preg_31_5', models.CharField(max_length=50, blank=True)),
                ('preg_31_6', models.CharField(max_length=50, blank=True)),
                ('preg_31_7', models.CharField(max_length=50, blank=True)),
                ('preg_31_8', models.CharField(max_length=50, blank=True)),
                ('preg_31_9', models.CharField(max_length=50, blank=True)),
                ('preg_31_10', models.CharField(max_length=50, blank=True)),
                ('preg_31_11', models.CharField(max_length=50, blank=True)),
                ('porque_preg_31_1', models.CharField(max_length=50, blank=True)),
                ('porque_preg_31_2', models.CharField(max_length=50, blank=True)),
                ('preg_32', models.CharField(max_length=50, blank=True)),
                ('preg_33_1', models.CharField(max_length=50, blank=True)),
                ('preg_33_2', models.CharField(max_length=50, blank=True)),
                ('preg_33_3', models.CharField(max_length=50, blank=True)),
                ('preg_33_4', models.CharField(max_length=50, blank=True)),
                ('preg_34_1', models.CharField(max_length=50, blank=True)),
                ('preg_34_2', models.CharField(max_length=50, blank=True)),
                ('preg_34_3', models.CharField(max_length=50, blank=True)),
                ('preg_34_4', models.CharField(max_length=50, blank=True)),
                ('preg_34_5', models.CharField(max_length=50, blank=True)),
                ('preg_34_6', models.CharField(max_length=50, blank=True)),
                ('preg_34_7', models.CharField(max_length=50, blank=True)),
                ('preg_34_8', models.CharField(max_length=50, blank=True)),
                ('preg_34_9', models.CharField(max_length=50, blank=True)),
                ('preg_34_10', models.CharField(max_length=50, blank=True)),
                ('preg_34_11', models.CharField(max_length=50, blank=True)),
                ('preg_34_12', models.CharField(max_length=50, blank=True)),
                ('preg_35_1', models.CharField(max_length=50, blank=True)),
                ('preg_35_2', models.CharField(max_length=50, blank=True)),
                ('preg_35_3', models.CharField(max_length=50, blank=True)),
                ('preg_35_4', models.CharField(max_length=50, blank=True)),
                ('preg_36', models.CharField(max_length=200, blank=True)),
                ('preg_37', models.CharField(max_length=200, blank=True)),
                ('preg_38_1', models.CharField(max_length=50, blank=True)),
                ('preg_38_2', models.CharField(max_length=50, blank=True)),
                ('preg_38_3', models.CharField(max_length=50, blank=True)),
                ('preg_38_4', models.CharField(max_length=50, blank=True)),
                ('preg_38_5', models.CharField(max_length=50, blank=True)),
                ('preg_39', models.CharField(max_length=100, blank=True)),
                ('preg_40', models.CharField(max_length=50, blank=True)),
                ('preg_41', models.CharField(max_length=50, blank=True)),
                ('porque_preg_41', models.CharField(max_length=200, blank=True)),
                ('preg_42', models.CharField(max_length=50, blank=True)),
                ('porque_preg_42', models.CharField(max_length=200, blank=True)),
                ('comentarios', models.CharField(max_length=200, blank=True)),
                ('alta_date_created', models.DateTimeField(auto_now_add=True)),
                ('baja_date_created', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='EncuestaEmpleador',
            fields=[
                ('id', models.AutoField(serialize=False, verbose_name='ID', auto_created=True, primary_key=True)),
                ('empresa', models.CharField(max_length=50, blank=True)),
                ('responsable', models.CharField(max_length=50, blank=True)),
                ('puesto', models.CharField(max_length=50, blank=True)),
                ('telefono', models.CharField(max_length=50, blank=True)),
                ('correo', models.CharField(max_length=50, blank=True)),
                ('preg_2', models.CharField(max_length=50, blank=True)),
                ('preg_3', models.CharField(max_length=50, blank=True)),
                ('preg_4', models.CharField(max_length=50, blank=True)),
                ('porque_preg_4', models.CharField(max_length=50, blank=True)),
                ('preg_5', models.CharField(max_length=200, blank=True)),
                ('preg_6', models.CharField(max_length=200, blank=True)),
                ('preg_7', models.CharField(max_length=200, blank=True)),
                ('preg_8_1', models.CharField(max_length=50, blank=True)),
                ('preg_8_2', models.CharField(max_length=50, blank=True)),
                ('preg_8_3', models.CharField(max_length=50, blank=True)),
                ('preg_8_4', models.CharField(max_length=50, blank=True)),
                ('preg_8_5', models.CharField(max_length=50, blank=True)),
                ('preg_8_6', models.CharField(max_length=50, blank=True)),
                ('preg_8_7', models.CharField(max_length=50, blank=True)),
                ('preg_8_8', models.CharField(max_length=50, blank=True)),
                ('preg_8_9', models.CharField(max_length=50, blank=True)),
                ('preg_8_10', models.CharField(max_length=50, blank=True)),
                ('preg_8_11', models.CharField(max_length=50, blank=True)),
                ('preg_8_12', models.CharField(max_length=50, blank=True)),
                ('preg_8_13', models.CharField(max_length=50, blank=True)),
                ('preg_8_14', models.CharField(max_length=50, blank=True)),
                ('preg_8_15', models.CharField(max_length=50, blank=True)),
                ('preg_8_16', models.CharField(max_length=50, blank=True)),
                ('preg_8_17', models.CharField(max_length=50, blank=True)),
                ('preg_8_18', models.CharField(max_length=50, blank=True)),
                ('preg_8_19', models.CharField(max_length=50, blank=True)),
                ('preg_8_20', models.CharField(max_length=50, blank=True)),
                ('preg_8_21', models.CharField(max_length=50, blank=True)),
                ('preg_8_22', models.CharField(max_length=50, blank=True)),
                ('preg_9', models.CharField(max_length=200, blank=True)),
                ('preg_10_1', models.CharField(max_length=50, blank=True)),
                ('preg_10_2', models.CharField(max_length=50, blank=True)),
                ('preg_10_3', models.CharField(max_length=50, blank=True)),
                ('preg_11', models.CharField(max_length=200, blank=True)),
                ('preg_12', models.CharField(max_length=200, blank=True)),
                ('preg_13', models.CharField(max_length=50, blank=True)),
                ('porque_preg_13', models.CharField(max_length=200, blank=True)),
                ('preg_14', models.CharField(max_length=200, blank=True)),
                ('comentarios', models.CharField(max_length=200, blank=True)),
                ('alta_date_created', models.DateTimeField(auto_now_add=True)),
                ('baja_date_created', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='EntregaDocumentos',
            fields=[
                ('id', models.AutoField(serialize=False, verbose_name='ID', auto_created=True, primary_key=True)),
                ('acta_nacimiento', models.SmallIntegerField(blank=True, null=True)),
                ('certificado_bachillerato', models.SmallIntegerField(blank=True, null=True)),
                ('certificado_final', models.SmallIntegerField(blank=True, null=True)),
                ('constancia_final', models.SmallIntegerField(blank=True, null=True)),
                ('constancia_servicio', models.SmallIntegerField(blank=True, null=True)),
                ('curp', models.SmallIntegerField(blank=True, null=True)),
                ('actividades_extracurriculares', models.SmallIntegerField(blank=True, null=True)),
                ('fotografia_titulo', models.SmallIntegerField(blank=True, null=True)),
                ('fotografia_certificado', models.SmallIntegerField(blank=True, null=True)),
                ('fotografia_infantil', models.SmallIntegerField(blank=True, null=True)),
                ('registro_cedula', models.SmallIntegerField(blank=True, null=True)),
                ('alta_date_created', models.DateTimeField(auto_now_add=True)),
                ('baja_date_created', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('alumno', models.ForeignKey(to='academica.Alumnos')),
            ],
            options={
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Equipos',
            fields=[
                ('id', models.AutoField(serialize=False, verbose_name='ID', auto_created=True, primary_key=True)),
                ('num_serie', models.CharField(max_length=50, blank=True)),
                ('nombre', models.CharField(max_length=50, blank=True)),
                ('alta_date_created', models.DateTimeField(auto_now_add=True)),
                ('baja_date_created', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Escuela',
            fields=[
                ('id', models.AutoField(serialize=False, verbose_name='ID', auto_created=True, primary_key=True)),
                ('localidad', models.CharField(max_length=50, blank=True, null=True)),
                ('nombre', models.CharField(max_length=100)),
                ('alta_date_created', models.DateTimeField(auto_now_add=True)),
                ('baja_date_created', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Estados',
            fields=[
                ('id', models.AutoField(serialize=False, verbose_name='ID', auto_created=True, primary_key=True)),
                ('nom_estado', models.CharField(max_length=50, blank=True)),
                ('clave', models.CharField(max_length=50, blank=True)),
                ('alta_date_created', models.DateTimeField(auto_now_add=True)),
                ('baja_date_created', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='activo')),
            ],
            options={
                'ordering': ['nom_estado'],
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Estatus',
            fields=[
                ('id', models.AutoField(serialize=False, verbose_name='ID', auto_created=True, primary_key=True)),
                ('nombre', models.CharField(max_length=50, blank=True)),
                ('alta_date_created', models.DateTimeField(auto_now_add=True)),
                ('baja_date_created', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Evaluacion',
            fields=[
                ('id', models.AutoField(serialize=False, verbose_name='ID', auto_created=True, primary_key=True)),
                ('alta_date_created', models.DateTimeField(auto_now_add=True)),
                ('baja_date_created', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('alumno', models.ForeignKey(to='academica.Alumnos')),
                ('calificacion', models.ForeignKey(to='academica.AlumnoCalificacion')),
            ],
            options={
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Extracurriculares',
            fields=[
                ('id', models.AutoField(serialize=False, verbose_name='ID', auto_created=True, primary_key=True)),
                ('nom_materia', models.CharField(max_length=50, blank=True, null=True)),
                ('clave', models.CharField(max_length=50, unique=True, blank=True, null=True)),
                ('tipo', models.CharField(max_length=50, blank=True, null=True)),
                ('alta_date_created', models.DateTimeField(auto_now_add=True)),
                ('baja_date_created', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='ExtraHorario',
            fields=[
                ('id', models.AutoField(serialize=False, verbose_name='ID', auto_created=True, primary_key=True)),
                ('lunes_hora', models.DateTimeField(blank=True, null=True)),
                ('martes_hora', models.DateTimeField(blank=True, null=True)),
                ('miercoles_hora', models.DateTimeField(blank=True, null=True)),
                ('jueves_hora', models.DateTimeField(blank=True, null=True)),
                ('viernes_hora', models.DateTimeField(blank=True, null=True)),
                ('lunes_duracion', models.DateTimeField(blank=True, null=True)),
                ('martes_duracion', models.DateTimeField(blank=True, null=True)),
                ('miercoles_duracion', models.DateTimeField(blank=True, null=True)),
                ('jueves_duracion', models.DateTimeField(blank=True, null=True)),
                ('viernes_duracion', models.DateTimeField(blank=True, null=True)),
                ('id_maestro', models.BigIntegerField(blank=True, null=True)),
                ('nom_horario', models.CharField(max_length=50, blank=True)),
                ('periodo', models.CharField(max_length=50, blank=True)),
                ('alta_date_created', models.DateTimeField(auto_now_add=True)),
                ('baja_date_created', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('extracurricular', models.ForeignKey(to='academica.Extracurriculares')),
            ],
            options={
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Grupos',
            fields=[
                ('id', models.AutoField(serialize=False, verbose_name='ID', auto_created=True, primary_key=True)),
                ('clave', models.CharField(max_length=50, unique=True, blank=True)),
                ('nombre', models.CharField(max_length=50, blank=True)),
                ('cant_alumnos', models.IntegerField(blank=True, null=True)),
                ('actual', models.SmallIntegerField(blank=True, null=True)),
                ('ciclo_escolar', models.CharField(max_length=50, blank=True)),
                ('alta_date_created', models.DateTimeField(auto_now_add=True)),
                ('baja_date_created', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['nombre'],
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.AutoField(serialize=False, verbose_name='ID', auto_created=True, primary_key=True)),
                ('clave_horario', models.CharField(max_length=20, blank=True, null=True)),
                ('nombre', models.CharField(max_length=20, blank=True, null=True)),
                ('hora_inicio', models.CharField(max_length=2, blank=True, null=True)),
                ('hora_termino', models.CharField(max_length=2, blank=True, null=True)),
                ('minutos_inicio', models.CharField(max_length=2, blank=True, null=True)),
                ('minutos_termino', models.CharField(max_length=2, blank=True, null=True)),
                ('alta_date_created', models.DateTimeField(verbose_name='Fecha', auto_now_add=True)),
                ('baja_date_created', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='activo')),
                ('aula', models.ForeignKey(to='academica.Aulas', blank=True, null=True)),
            ],
            options={
                'ordering': ['aula'],
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Inscripciones',
            fields=[
                ('id', models.AutoField(serialize=False, verbose_name='ID', auto_created=True, primary_key=True)),
                ('alta_date_created', models.DateTimeField(auto_now_add=True)),
                ('baja_date_created', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('alumno', models.ForeignKey(to='academica.Alumnos')),
                ('semestre', models.ForeignKey(to='academica.CicloSemestral')),
            ],
            options={
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Jefes',
            fields=[
                ('id', models.AutoField(serialize=False, verbose_name='ID', auto_created=True, primary_key=True)),
                ('nom_jefe', models.CharField(max_length=50, blank=True)),
                ('puesto', models.CharField(max_length=50, blank=True)),
                ('firma', models.BinaryField(blank=True, null=True)),
                ('alta_date_created', models.DateTimeField(auto_now_add=True)),
                ('baja_date_created', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='JefesDivision',
            fields=[
                ('id', models.AutoField(serialize=False, verbose_name='ID', auto_created=True, primary_key=True)),
                ('nombre', models.CharField(max_length=50, blank=True)),
                ('alta_date_created', models.DateTimeField(auto_now_add=True)),
                ('baja_date_created', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('division', models.ForeignKey(to='academica.Divisiones')),
            ],
            options={
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='LaboratorioComputo',
            fields=[
                ('id', models.AutoField(serialize=False, verbose_name='ID', auto_created=True, primary_key=True)),
                ('nom_laboratorio', models.CharField(max_length=50, blank=True)),
                ('alta_date_created', models.DateTimeField(auto_now_add=True)),
                ('baja_date_created', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='LiberacionDocumentos',
            fields=[
                ('id', models.AutoField(serialize=False, verbose_name='ID', auto_created=True, primary_key=True)),
                ('acta_nacimiento', models.SmallIntegerField(blank=True, null=True)),
                ('certificado_bachillerato', models.SmallIntegerField(blank=True, null=True)),
                ('certificado_final', models.SmallIntegerField(blank=True, null=True)),
                ('constancia_final', models.SmallIntegerField(blank=True, null=True)),
                ('constancia_servicio', models.SmallIntegerField(blank=True, null=True)),
                ('curp', models.SmallIntegerField(blank=True, null=True)),
                ('alta_date_created', models.DateTimeField(auto_now_add=True)),
                ('baja_date_created', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('alumno', models.ForeignKey(to='academica.Alumnos')),
            ],
            options={
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Maestros',
            fields=[
                ('id', models.AutoField(serialize=False, verbose_name='ID', auto_created=True, primary_key=True)),
                ('nombre', models.CharField(max_length=50, blank=True)),
                ('no_expediente', models.CharField(max_length=50, blank=True, verbose_name='Numero de Empleado')),
                ('alta_date_created', models.DateTimeField(auto_now_add=True)),
                ('baja_date_created', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['nombre'],
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Materias',
            fields=[
                ('id', models.AutoField(serialize=False, verbose_name='ID', auto_created=True, primary_key=True)),
                ('nom_materia', models.CharField(max_length=50, blank=True)),
                ('clave', models.CharField(max_length=50, unique=True, blank=True)),
                ('seriacion', models.CharField(max_length=50, blank=True, verbose_name='Serialización')),
                ('creditos', models.IntegerField(blank=True, null=True)),
                ('alta_date_created', models.DateTimeField(auto_now_add=True)),
                ('baja_date_created', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['nom_materia'],
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Municipios',
            fields=[
                ('id', models.AutoField(serialize=False, verbose_name='ID', auto_created=True, primary_key=True)),
                ('nom_municipio', models.CharField(max_length=50, blank=True)),
                ('alta_date_created', models.DateTimeField(auto_now_add=True)),
                ('baja_date_created', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('estado', models.ForeignKey(to='academica.Estados', blank=True, null=True)),
            ],
            options={
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Personas',
            fields=[
                ('id', models.AutoField(serialize=False, verbose_name='ID', auto_created=True, primary_key=True)),
                ('nom_persona', models.CharField(max_length=50, blank=True)),
                ('edad', models.IntegerField(blank=True, null=True)),
                ('alta_date_created', models.DateTimeField(auto_now_add=True)),
                ('baja_date_created', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='PlanEstudio',
            fields=[
                ('id', models.AutoField(serialize=False, verbose_name='ID', auto_created=True, primary_key=True)),
                ('nom_plan', models.CharField(max_length=50, blank=True)),
                ('clave_plan', models.CharField(max_length=50, unique=True, blank=True)),
                ('alta_date_created', models.DateTimeField(auto_now_add=True)),
                ('baja_date_created', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('materias', models.ManyToManyField(to='academica.Materias', blank=True, null=True)),
            ],
            options={
                'ordering': ['nom_plan'],
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Privilegios',
            fields=[
                ('id', models.AutoField(serialize=False, verbose_name='ID', auto_created=True, primary_key=True)),
                ('privilegio', models.CharField(max_length=50, blank=True)),
                ('alta_date_created', models.DateTimeField(auto_now_add=True)),
                ('baja_date_created', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='ProgramacionExamen',
            fields=[
                ('id', models.AutoField(serialize=False, verbose_name='ID', auto_created=True, primary_key=True)),
                ('alta_date_created', models.DateTimeField(auto_now_add=True)),
                ('baja_date_created', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('alumno', models.ForeignKey(to='academica.Alumnos')),
            ],
            options={
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='ReservacionAlumno',
            fields=[
                ('id', models.AutoField(serialize=False, verbose_name='ID', auto_created=True, primary_key=True)),
                ('alumno', models.BigIntegerField(blank=True, null=True)),
                ('equipo', models.BigIntegerField(blank=True, null=True)),
                ('alta_date_created', models.DateTimeField(auto_now_add=True)),
                ('baja_date_created', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='ReservacionMaestroEsporadico',
            fields=[
                ('id', models.AutoField(serialize=False, verbose_name='ID', auto_created=True, primary_key=True)),
                ('alta_date_created', models.DateTimeField(auto_now_add=True)),
                ('baja_date_created', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('laboratorio', models.ForeignKey(to='academica.LaboratorioComputo', blank=True, null=True)),
                ('maestro', models.ForeignKey(to='academica.Maestros', blank=True, null=True)),
            ],
            options={
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='ReservacionMaestroFijo',
            fields=[
                ('id', models.AutoField(serialize=False, verbose_name='ID', auto_created=True, primary_key=True)),
                ('hora_lunes_inicio', models.DateTimeField(blank=True, null=True)),
                ('hora_martes_inicio', models.DateTimeField(blank=True, null=True)),
                ('hora_miercoles_inicio', models.DateTimeField(blank=True, null=True)),
                ('hora_jueves_inicio', models.DateTimeField(blank=True, null=True)),
                ('hora_viernes_inicio', models.DateTimeField(blank=True, null=True)),
                ('hora_lunes_fin', models.DateTimeField(blank=True, null=True)),
                ('hora_martes_fin', models.DateTimeField(blank=True, null=True)),
                ('hora_miercoles_fin', models.DateTimeField(blank=True, null=True)),
                ('hora_jueves_fin', models.DateTimeField(blank=True, null=True)),
                ('hora_viernes_fin', models.DateTimeField(blank=True, null=True)),
                ('alta_date_created', models.DateTimeField(auto_now_add=True)),
                ('baja_date_created', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('laboratorio', models.ForeignKey(to='academica.LaboratorioComputo', blank=True, null=True)),
                ('maestro', models.ForeignKey(to='academica.Maestros', blank=True, null=True)),
            ],
            options={
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Revalidaciones',
            fields=[
                ('id', models.AutoField(serialize=False, verbose_name='ID', auto_created=True, primary_key=True)),
                ('tipo', models.CharField(max_length=50, blank=True)),
                ('alta_date_created', models.DateTimeField(auto_now_add=True)),
                ('baja_date_created', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('alumno', models.ForeignKey(to='academica.Alumnos')),
                ('materia', models.ForeignKey(to='academica.Materias')),
            ],
            options={
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Semestre',
            fields=[
                ('id', models.AutoField(serialize=False, verbose_name='ID', auto_created=True, primary_key=True)),
                ('clave', models.CharField(max_length=50, unique=True, blank=True)),
                ('alta_date_created', models.DateTimeField(auto_now_add=True)),
                ('baja_date_created', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('ciclo_semestral', models.ForeignKey(to='academica.CicloSemestral', to_field='clave')),
            ],
            options={
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='ServicioEstadia',
            fields=[
                ('id', models.AutoField(serialize=False, verbose_name='ID', auto_created=True, primary_key=True)),
                ('nombre', models.CharField(max_length=50, blank=True)),
                ('asesor_interno', models.CharField(max_length=50, blank=True)),
                ('asesor_externo', models.CharField(max_length=50, blank=True)),
                ('tipo', models.CharField(max_length=50, blank=True)),
                ('alta_date_created', models.DateTimeField(auto_now_add=True)),
                ('baja_date_created', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('empresa', models.ForeignKey(to='academica.Empresas')),
            ],
            options={
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='ServicioHoras',
            fields=[
                ('id', models.AutoField(serialize=False, verbose_name='ID', auto_created=True, primary_key=True)),
                ('horas', models.IntegerField(blank=True, null=True)),
                ('alta_date_created', models.DateTimeField(auto_now_add=True)),
                ('baja_date_created', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='liberar')),
                ('alumno', models.ForeignKey(to='academica.Alumnos', unique=True)),
                ('proyecto', models.ForeignKey(to='academica.ServicioEstadia')),
            ],
            options={
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Servicios',
            fields=[
                ('id', models.AutoField(serialize=False, verbose_name='ID', auto_created=True, primary_key=True)),
                ('nombre', models.CharField(max_length=50, blank=True)),
                ('alta_date_created', models.DateTimeField(auto_now_add=True)),
                ('baja_date_created', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='SolicitudBeca',
            fields=[
                ('id', models.AutoField(serialize=False, verbose_name='ID', auto_created=True, primary_key=True)),
                ('alta_date_created', models.DateTimeField(auto_now_add=True)),
                ('baja_date_created', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('alumno', models.ForeignKey(to='academica.Alumnos')),
                ('beca', models.ForeignKey(to='academica.Becas')),
            ],
            options={
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Sysdiagrams',
            fields=[
                ('id', models.AutoField(serialize=False, verbose_name='ID', auto_created=True, primary_key=True)),
                ('name', models.CharField(max_length=1)),
                ('principal', models.IntegerField()),
                ('version', models.IntegerField(blank=True, null=True)),
                ('definition', models.BinaryField(blank=True, null=True)),
                ('alta_date_created', models.DateTimeField(auto_now_add=True)),
                ('baja_date_created', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='TemasTitulo',
            fields=[
                ('id', models.AutoField(serialize=False, verbose_name='ID', auto_created=True, primary_key=True)),
                ('nombre', models.CharField(max_length=50, blank=True)),
                ('aceptado', models.SmallIntegerField(blank=True, null=True)),
                ('asesor', models.CharField(max_length=50, blank=True)),
                ('alta_date_created', models.DateTimeField(auto_now_add=True)),
                ('baja_date_created', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('alumno', models.ForeignKey(to='academica.Alumnos')),
            ],
            options={
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='TipoBeca',
            fields=[
                ('id', models.AutoField(serialize=False, verbose_name='ID', auto_created=True, primary_key=True)),
                ('clave_tipo_beca', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.CharField(max_length=250)),
                ('alta_date_created', models.DateTimeField(auto_now_add=True)),
                ('baja_date_created', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Titulos',
            fields=[
                ('id', models.AutoField(serialize=False, verbose_name='ID', auto_created=True, primary_key=True)),
                ('hora_inicio', models.DateTimeField(blank=True, null=True)),
                ('hora_fin', models.DateTimeField(blank=True, null=True)),
                ('dictamen', models.CharField(max_length=50, blank=True)),
                ('no_foja', models.IntegerField(blank=True, null=True)),
                ('tipo_folio', models.CharField(max_length=50, blank=True)),
                ('no_libro', models.CharField(max_length=50, blank=True)),
                ('alta_date_created', models.DateTimeField(auto_now_add=True)),
                ('baja_date_created', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('tema', models.ForeignKey(to='academica.TemasTitulo')),
            ],
            options={
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='TmpAlumnoServicio',
            fields=[
                ('id', models.AutoField(serialize=False, verbose_name='ID', auto_created=True, primary_key=True)),
                ('horas', models.IntegerField(blank=True, null=True)),
                ('alta_date_created', models.DateTimeField(auto_now_add=True)),
                ('baja_date_created', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('alumno', models.ForeignKey(to='academica.Alumnos', blank=True, null=True)),
            ],
            options={
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='TmpAlumnosEstadias',
            fields=[
                ('id', models.AutoField(serialize=False, verbose_name='ID', auto_created=True, primary_key=True)),
                ('alta_date_created', models.DateTimeField(auto_now_add=True)),
                ('baja_date_created', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('alumno', models.ForeignKey(to='academica.Alumnos', blank=True, null=True)),
            ],
            options={
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Tramites',
            fields=[
                ('id', models.AutoField(serialize=False, verbose_name='ID', auto_created=True, primary_key=True)),
                ('monto', models.DecimalField(max_digits=18, blank=True, null=True, decimal_places=2)),
                ('alta_date_created', models.DateTimeField(auto_now_add=True)),
                ('baja_date_created', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('alumno', models.ForeignKey(to='academica.Alumnos')),
                ('estatus', models.ForeignKey(to='academica.Estatus')),
                ('servicio', models.ForeignKey(to='academica.Servicios')),
            ],
            options={
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.AutoField(serialize=False, verbose_name='ID', auto_created=True, primary_key=True)),
                ('usuario', models.CharField(max_length=50, blank=True)),
                ('password', models.CharField(max_length=100, blank=True)),
                ('alta_date_created', models.DateTimeField(auto_now_add=True)),
                ('baja_date_created', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('maestro', models.ForeignKey(to='academica.Maestros')),
                ('privilegio', models.ForeignKey(to='academica.Privilegios')),
            ],
            options={
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='UsuariosLab',
            fields=[
                ('id', models.AutoField(serialize=False, verbose_name='ID', auto_created=True, primary_key=True)),
                ('usuario', models.CharField(max_length=50, blank=True)),
                ('password', models.CharField(max_length=50, blank=True)),
                ('alta_date_created', models.DateTimeField(auto_now_add=True)),
                ('baja_date_created', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
            },
            bases=(models.Model,),
        ),
        migrations.AddField(
            model_name='tmpalumnosestadias',
            name='user',
            field=models.ForeignKey(to='academica.Usuarios', blank=True, null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='tmpalumnoservicio',
            name='user',
            field=models.ForeignKey(to='academica.Usuarios', blank=True, null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='materias',
            name='semestre',
            field=models.ForeignKey(to_field='clave', to='academica.Semestre', blank=True, null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='jefesdivision',
            name='usuario',
            field=models.ForeignKey(to='academica.Usuarios', blank=True, null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='horario',
            name='profesores',
            field=models.ForeignKey(to='academica.Maestros', blank=True, null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='grupos',
            name='horarios',
            field=models.ManyToManyField(to='academica.Horario', blank=True, null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='grupos',
            name='plan',
            field=models.ForeignKey(to_field='clave_plan', to='academica.PlanEstudio', blank=True, null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='grupos',
            name='semestre',
            field=models.ForeignKey(to_field='clave', to='academica.CicloSemestral', blank=True, null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='evaluacion',
            name='materia',
            field=models.ForeignKey(to='academica.Materias'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='escuela',
            name='estado',
            field=models.ForeignKey(to='academica.Estados'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='equipos',
            name='laboratorio',
            field=models.ForeignKey(to='academica.LaboratorioComputo', blank=True, null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='cursos',
            name='personas',
            field=models.ManyToManyField(to='academica.Personas', blank=True, null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='carreras',
            name='plan_estudio',
            field=models.ForeignKey(to='academica.PlanEstudio', blank=True, null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='calificaciones',
            name='materia',
            field=models.ForeignKey(to='academica.Materias', to_field='clave', null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='calificaciones',
            name='matricula',
            field=models.ForeignKey(to='academica.Alumnos', to_field='matricula', null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='calificaciones',
            name='plan',
            field=models.ForeignKey(to='academica.PlanEstudio', to_field='clave_plan', null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='calificaciones',
            name='semestre',
            field=models.ForeignKey(to='academica.CicloSemestral', to_field='clave', null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='becas',
            name='tipo_beca',
            field=models.ForeignKey(to='academica.TipoBeca', to_field='clave_tipo_beca'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='bajas',
            name='ciclo',
            field=models.ForeignKey(to_field='clave', to='academica.CicloSemestral', blank=True, null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='bajas',
            name='matricula',
            field=models.ForeignKey(to_field='matricula', to='academica.Alumnos', blank=True, null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='alumnos',
            name='carrera',
            field=models.ForeignKey(to_field='clave', to='academica.Carreras', blank=True, null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='alumnos',
            name='escuela_procedencia',
            field=models.ForeignKey(null=True, to='academica.Escuela', blank=True, verbose_name='Escuela'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='alumnos',
            name='extracurriculares',
            field=models.ManyToManyField(to='academica.Extracurriculares', blank=True, null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='alumnos',
            name='grupo',
            field=models.ForeignKey(to_field='clave', to='academica.Grupos', blank=True, null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='alumnos',
            name='plan',
            field=models.ForeignKey(to_field='clave_plan', to='academica.PlanEstudio', blank=True, null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='alumnos',
            name='semestre',
            field=models.ForeignKey(to_field='clave', to='academica.CicloSemestral', blank=True, null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='alumnoproyecto',
            name='alumno',
            field=models.ForeignKey(to='academica.Alumnos', blank=True, null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='alumnoproyecto',
            name='proyecto',
            field=models.ForeignKey(to='academica.ServicioEstadia', blank=True, null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='alumnoprevio',
            name='alumno',
            field=models.ForeignKey(to='academica.Alumnos', unique=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='alumnocalificacion',
            name='horario',
            field=models.ForeignKey(to='academica.Horario', blank=True, null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='alumnocalificacion',
            name='semestre',
            field=models.ForeignKey(to='academica.CicloSemestral'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='aceptados',
            name='alumno_previo',
            field=models.ForeignKey(to='academica.AlumnoPrevio', blank=True, null=True),
            preserve_default=True,
        ),
    ]
